variables:
  DENO_VERSION: v0.2.8

jobs:

- job: Linux
  pool:
    vmImage: Ubuntu-16.04
  steps:
  - script: curl -L https://deno.land/x/install/install.py | python - $(DENO_VERSION)
  - script: echo '##vso[task.prependpath]$(HOME)/.deno/bin/'
  - script: deno --allow-run main_test.ts

- job: Mac
  pool:
    vmImage: macOS-10.13
  steps:
  - script: curl -L https://deno.land/x/install/install.py | python - $(DENO_VERSION)
  - script: echo '##vso[task.prependpath]$(HOME)/.deno/bin/'
  - script: deno --allow-run main_test.ts

- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - powershell: iwr https://deno.land/x/install/install.ps1 -Outfile 'install.ps1'; ./install.ps1 $(DENO_VERSION)
  - script: echo '##vso[task.prependpath]C:\Users\VssAdministrator\.deno\bin\'
  - script: 'C:\Users\VssAdministrator\.deno\bin\deno.exe --allow-run main_test.ts'
